[package]
name = "example_bevy_project"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.3"
nest_editor_shared = { path = "../../crates/nest_editor_shared" }

[lib]
crate-type = ["cdylib", "rlib"]

[profile.dev]
lto = false
strip = false